# Generated by Django 3.2.9 on 2021-12-30 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_name', models.CharField(max_length=300)),
                ('cell_address', models.CharField(max_length=300)),
                ('cell_date_founded', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=25)),
                ('middle_name', models.CharField(blank=True, default='', max_length=25)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('state_of_origin', models.CharField(blank=True, choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(default=datetime.datetime.now)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=300)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('wing', models.CharField(blank=True, choices=[('Youth', 'Youth'), ('Men', 'Men'), ('Women', 'Women')], max_length=25)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('home_cell', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='member_app.homecell')),
            ],
            options={
                'ordering': ['date_joined'],
            },
        ),
        migrations.AddField(
            model_name='homecell',
            name='cell_leader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homecell_set', to='member_app.member'),
        ),
    ]
