# Generated by Django 3.2.9 on 2021-12-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='home_cell',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='member_app.homecell'),
        ),
    ]
