# Generated by Django 3.2.9 on 2021-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birth_month',
        ),
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
