# Generated by Django 3.2.9 on 2021-12-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0002_alter_member_home_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='cell_leader',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='homecell_set', to='member_app.member'),
        ),
    ]
