# Generated by Django 3.2.9 on 2021-12-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0003_alter_homecell_cell_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='cell_leader',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homecell_set', to='member_app.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_cell',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='member_app.homecell'),
        ),
    ]
