# Generated by Django 3.2.9 on 2022-01-02 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0004_auto_20211230_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('sunday_service', models.BooleanField()),
                ('tuesday_h_d', models.BooleanField()),
                ('wednesday_service', models.BooleanField()),
                ('others', models.BooleanField()),
                ('first_service', models.BooleanField(default=False)),
                ('second_service', models.BooleanField(default=False)),
                ('third_service', models.BooleanField(default=False)),
                ('no_of_men', models.PositiveIntegerField(default=0)),
                ('no_of_women', models.PositiveIntegerField(default=0)),
                ('no_of_children', models.PositiveIntegerField(default=0)),
                ('no_of_new_comers', models.PositiveIntegerField(default=0)),
                ('no_of_new_converts', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=300),
        ),
    ]
