# Generated by Django 3.2.9 on 2022-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0006_auto_20220102_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberattendance',
            name='service',
            field=models.CharField(choices=[('Sunday Service', 'Sunday Service'), ('Tueday Healing & Deliverance', 'Tuesday Healing & Deliverance'), ('Wednesday Mid-Week Service', 'Wednesday Mid-Week Service'), ('Friday Worship & Wonders Night', 'Friday Worship & Wonders Night'), ('Others', 'Others')], default='Sunday Service', max_length=70),
        ),
    ]
