# Generated by Django 3.2.9 on 2022-01-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0008_auto_20220102_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCount',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='memberattendance',
            old_name='service_type',
            new_name='service_Type',
        ),
        migrations.RemoveField(
            model_name='memberattendance',
            name='service',
        ),
    ]
