# Generated by Django 3.2.9 on 2022-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0011_auto_20220102_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='overall_total',
        ),
        migrations.AddField(
            model_name='memberattendance',
            name='overall_total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
