# Generated by Django 3.2.9 on 2022-01-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0013_alter_memberattendance_overall_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ['date']},
        ),
    ]
