# Generated by Django 3.2.9 on 2022-01-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0014_alter_memberattendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberattendance',
            options={'ordering': ['-date']},
        ),
    ]
