# Generated by Django 3.2.9 on 2022-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0016_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
