# Generated by Django 3.2.9 on 2022-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0018_alter_member_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, choices=[('Media', 'Media'), ('Choir', 'Choir'), ('Sanctuary', 'Sanctuary')], default='Media', max_length=100),
        ),
    ]
