# Generated by Django 3.2.9 on 2022-01-15 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0019_alter_member_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=11)),
                ('recipients', models.TextField(max_length=50000000000)),
                ('message_text', models.CharField(max_length=918)),
                ('flash', models.BooleanField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('approved_message', models.BooleanField(default=False)),
                ('sent_date', models.DateField()),
            ],
        ),
    ]
