# Generated by Django 3.2.9 on 2022-01-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0020_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(max_length=918),
        ),
    ]
