# Generated by Django 3.2.9 on 2022-01-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0022_alter_message_approved_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='approved_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='flash',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
