# Generated by Django 3.2.9 on 2022-01-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0024_alter_message_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
