# Generated by Django 3.2.9 on 2022-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0026_auto_20220116_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='flash',
            field=models.BooleanField(choices=[(True, True), (False, True)], default=False),
        ),
    ]
