# Generated by Django 3.2.9 on 2022-01-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0027_alter_message_flash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='flash',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
