# Generated by Django 3.2.9 on 2022-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0028_alter_message_flash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
