# Generated by Django 3.2.9 on 2022-01-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0029_alter_message_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.CharField(choices=[('Member', 'Member'), ('New Member', 'New Member'), ('Guest', 'Guest'), ('Former Member', 'Former Member')], default='Member', max_length=25),
        ),
    ]
