# Generated by Django 3.2.9 on 2022-01-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0033_alter_member_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
