# Generated by Django 3.2.9 on 2022-01-19 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0036_alter_member_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_updated',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
