# Generated by Django 3.2.9 on 2022-01-19 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0039_alter_member_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(editable=False, verbose_name=datetime.datetime.now),
        ),
    ]
