# Generated by Django 3.2.9 on 2022-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0042_alter_member_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='other_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
