# Generated by Django 3.2.9 on 2022-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0044_auto_20220119_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_age',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
