# Generated by Django 3.2.9 on 2022-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0045_alter_member_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='done_foundation',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='done_maturity',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_baptized',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
