# Generated by Django 3.2.9 on 2022-01-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0046_auto_20220120_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_baptized',
            field=models.BooleanField(choices=[(True, 'Baptized'), (False, 'Not Yet')], default=True),
        ),
    ]
