# Generated by Django 3.2.9 on 2022-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0047_alter_member_is_baptized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
