# Generated by Django 3.2.9 on 2022-01-20 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0050_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='All Values Must Be A Number', regex='^\\d{1,10}$')]),
        ),
    ]
