# Generated by Django 3.2.9 on 2022-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0052_auto_20220121_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
