# Generated by Django 3.2.9 on 2022-01-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0053_alter_member_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_joined']},
        ),
    ]
