# Generated by Django 3.2.9 on 2022-01-21 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0054_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecell',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='homecell',
            name='cell_date_founded',
        ),
        migrations.AddField(
            model_name='homecell',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='homecell',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
