# Generated by Django 3.2.9 on 2022-01-21 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0055_auto_20220121_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecell',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='homecell',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
