# Generated by Django 3.2.9 on 2022-01-21 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0056_auto_20220121_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 2, 30, 348647)),
        ),
    ]
