# Generated by Django 3.2.9 on 2022-01-21 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0057_alter_homecell_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 23, 25, 55, 530467)),
        ),
    ]
