# Generated by Django 3.2.9 on 2022-01-21 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0058_alter_homecell_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
