# Generated by Django 3.2.9 on 2022-01-21 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0059_alter_homecell_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='cell_leader',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homecell_rel', to='member_app.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_cell',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_rel', to='member_app.homecell'),
        ),
    ]
