# Generated by Django 3.2.9 on 2022-01-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0060_auto_20220122_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecell',
            name='cell_leader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homecell_rel', to='member_app.member'),
        ),
    ]
