# Generated by Django 3.2.9 on 2021-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='new',
            field=models.CharField(default='New', max_length=70),
        ),
    ]
