# Generated by Django 3.2.9 on 2021-12-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_app', '0002_lyrics_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='new',
        ),
    ]
