# Generated by Django 3.2.9 on 2021-12-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_app', '0010_alter_lyrics_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='category',
            field=models.CharField(choices=[('Praise Song', 'Praise Song'), ('Worship Song', 'Worship Song'), ('Christmas Song', 'Christmas Song'), ('Dr. Paul Song', 'Dr. Paul Song'), ('Hymn', 'Hymn')], default='Hymn', max_length=50),
        ),
    ]
