# Generated by Django 3.2.9 on 2021-12-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_app', '0012_alter_lyrics_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lyrics',
            options={'ordering': ['-date_added']},
        ),
    ]
