# Generated by Django 3.2.9 on 2021-12-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_app', '0002_alter_member_home_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCellMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('town', models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City')),
                ('county', models.CharField(blank=True, max_length=100, null=True, verbose_name='County')),
                ('post_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Post Code')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('has_cell', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('cell_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allcellmembers_set', to='member_app.member')),
            ],
        ),
    ]
